language: python
cache: pip
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "nightly"
  - "pypy-5.4"
  - "pypy3"

matrix:
  # pypy3 latest version is not playing nice.
  allow_failures:
    - python: "pypy3"
    - python: "nightly"

before_install:
  # Install codecov
  - if [[ $TRAVIS_PYTHON_VERSION == '3.2' ]]; then pip install coverage==3.7.1; fi
  - pip install codecov

install:
  - pip install six
  - if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then pip install unittest2; fi
  - ./ci_tools/retry.sh python updatezinfo.py

script:
  - coverage run --omit=setup.py,dateutil/test/* setup.py test

after_success:
  - codecov

sudo: false
